name: Unit Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
          extensions: sqlite3, pdo_sqlite
          coverage: pcov

      - uses: actions/checkout@v4

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Generate Key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Run Unit Tests
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: :memory:
        run: php artisan test --no-coverage

      - name: Run Unit Tests with Coverage
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: :memory:
        run: php artisan test --coverage --min=80
        if: github.event_name == 'pull_request'

